#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 450206-web-01 54.152.60.211:80 check\n\tserver 450206-web-02 3.86.13.92:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
